# CheaterCheck - Конфигурация
# Основные настройки плагина для проверки читеров

# Настройки сообщений
messages:
  prefix: '&8[&c&lCheaterCheck&8] &r'
  freeze:
    frozen: '&cВы были заморожены администратором для проверки. Пожалуйста, ожидайте.'
    frozen-staff: '&aИгрок &e{player} &aбыл заморожен для проверки.'
    unfrozen: '&aВы были разморожены.'
    unfrozen-staff: '&aИгрок &e{player} &aбыл разморожен.'
    already-frozen: '&cИгрок &e{player} &cуже заморожен.'
    not-frozen: '&cИгрок &e{player} &cне заморожен.'
    prevent-commands: '&cВы не можете использовать команды во время проверки!'
    prevent-interaction: '&cВы не можете взаимодействовать с предметами во время проверки!'
    prevent-movement: '&cВы не можете двигаться во время проверки!'
  screenshare:
    request-sent: '&aЗапрос скриншера отправлен игроку &e{player}&a.'
    request-received: '&c&lВы должны предоставить скриншер! &7Используйте Discord: &b&l{discord}'
    completed: '&aПроверка игрока &e{player} &aзавершена.'
  check:
    started: '&aНачата проверка игрока &e{player}&a.'
    completed: '&aПроверка игрока &e{player} &aзавершена.'
    result-clean: '&aИгрок &e{player} &aбыл проверен и признан чистым.'
    result-banned: '&cИгрок &e{player} &cбыл забанен за использование чита &e{cheat}&c.'
    reload: '&aПлагин был успешно перезагружен!'
    # Повторяющееся сообщение для подозреваемого (каждые 10 секунд)
    suspect-reminder: '&c&lВНИМАНИЕ! &eВы находитесь на проверке! Пожалуйста, выполняйте указания администратора. &c&lНе выходите с сервера!'
    # Настройки для Title при вызове на проверку
    title:
      main: '&c&lВы вызваны на проверку'
      subtitle: '&7Выполняйте действия проверяющего'
      fade-in: 10
      stay: 70
      fade-out: 20
  error:
    player-not-found: '&cИгрок не найден!'
    no-permission: '&cУ вас нет прав для этой команды!'
    bypass-list: '&cИгрок &e{player} &cнаходится в списке игроков, которых нельзя проверить!'

# Настройки заморозки
freeze:
  # Радиус для блокировки телепортации (блоки)
  freeze-radius: 2
  # Отображать частицы вокруг замороженного игрока
  particles: true
  # Тип частиц (SMOKE, FLAME, HEART, REDSTONE и т.д.)
  particle-type: BARRIER
  # Блокировать все команды для замороженного игрока
  block-commands: true
  # Разрешенные команды во время заморозки
  allowed-commands:
    - 'msg'
    - 'r'
    - 'tell'
    - 'me'
  # Звук при заморозке игрока
  sound:
    enabled: true
    name: BLOCK_GLASS_BREAK
    volume: 1.0
    pitch: 1.0
  # Автоматический бан при выходе во время проверки
  auto-ban-on-quit: true
  # Выдавать эффект слепоты при заморозке
  blindness-effect: true
  # Настройки телепортации на координаты проверки
  teleport:
    enabled: true
    world: 'world'
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
  # Настройки частиц
  particles:
    # Включить частицы вокруг замороженных игроков
    enabled: true
    # Тип частиц
    # Список частиц: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
    type: "SMOKE_NORMAL"
  # Настройки эффектов
  effects:
    # Применять эффект слепоты при заморозке
    blindness: false
  # Автоматически телепортировать игрока на землю при заморозке, если он в воздухе
  teleport-to-ground: true

# Настройки проверки
check:
  # Название Discord-сервера или ссылка для общения во время проверки
  discord: 'https://discord.gg/your-server'
  # Время в секундах до автобана, если игрок не отвечает (0 - отключено)
  timeout: 300
  # Отправлять сообщение всем администраторам при начале проверки
  notify-staff: true
  # Отправлять сообщение всем игрокам при бане читера
  public-ban-message: true
  # Интервал повторения сообщения для подозреваемого (в секундах)
  reminder-interval: 30
  # Настройки периодического Title
  periodic-title:
    # Включить периодическое отображение заголовка
    enabled: true
    # Интервал в секундах между отображениями
    interval: 60
    # Продолжительность отображения в секундах
    duration: 5
  # Проверка на AFK
  afk-check:
    # Включить проверку на AFK
    enabled: true
    # Время в секундах, после которого игрок считается AFK
    timeout: 60
    # Сообщение при попытке проверки AFK игрока
    message: '&cИгрок &e{player} &cв данный момент AFK! Дождитесь его возвращения.'
  # Команда, выполняемая при бане
  ban-command: 'ban {player} Использование чита: {cheat}'
  # Команда, выполняемая при выходе игрока с сервера во время проверки
  quit-command: 'ban {player} Выход во время проверки'
  # Команды, выполняемые при начале проверки для подозреваемого
  start-commands:
    - 'effect give {player} minecraft:slowness 999999 1 true'
    - 'effect give {player} minecraft:weakness 999999 1 true'
  # Команды, выполняемые при окончании проверки для подозреваемого
  stop-commands:
    - 'effect clear {player}'
  # Время ожидания (в секундах) перед автоматической разморозкой игрока
  timeoutSeconds: 300
  # Отправлять ли сообщение о начале проверки всем игрокам
  broadcastStartMessage: true
  # Использовать право на обход проверки
  useBypassPermission: true
  # Право для обхода проверки
  bypassPermission: "cheatercheck.bypass"
  # Настройки телепортации
  teleport:
    # Включить телепортацию при проверке
    enabled: true
    # Локация для телепортации
    # Устанавливается через команду /setchecklocation
    location:
      world: 'world'
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0
  # Таймаут проверки (в секундах)
  timeoutSeconds: 300
  
  # Автоматический бан при истечении времени
  timeout:
    autoban: true
    
  # Команда, которая будет выполнена, если время проверки истекло
  timeoutCommand: "tempban {player} 1d Выход во время проверки"
  
  # Периодическое напоминание для проверяемого игрока
  reminderInterval: 30 # Интервал в секундах (0 для отключения)
  
  # Периодическое отображение заголовка
  periodicTitle:
    enabled: true
    interval: 15 # Интервал в секундах
  
  # Настройки заголовка при проверке
  title:
    main: "&c&lВНИМАНИЕ!"
    subtitle: "&eВы находитесь на проверке!"
    fadeIn: 10  # тики
    stay: 70    # тики
    fadeOut: 20 # тики
  
  # Сообщения
  messages:
    suspectReminder: "&c&lНа вас поступила жалоба. Пожалуйста, выполните требования администратора!"
  
  # Настройки босс-бара
  bossbar:
    enabled: true
    style: "SEGMENTED_10" # SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20

# Интеграция с другими плагинами
integrations:
  # LiteBans, AdvancedBan, BanManager и т.д.
  ban-plugin: 'vanilla'

# Настройки отображения Title
title:
  # Основной текст Title
  main: "&c&lВЫ НА ПРОВЕРКЕ"
  
  # Подзаголовок Title
  subtitle: "&e&lОтветьте администратору в чат"
  
  # Время появления в тиках (20 тиков = 1 секунда)
  fade-in: 10
  
  # Время отображения в тиках
  stay: 70
  
  # Время исчезновения в тиках
  fade-out: 20
  
  # Периодическое отображение Title
  periodic:
    # Включить периодические Title
    enabled: true
    
    # Интервал между отображениями в секундах
    interval: 60
    
    # Продолжительность отображения в секундах
    duration: 5

# Настройки проверки на AFK
afk:
  # Включить проверку на AFK
  enabled: true
  
  # Время в секундах, после которого игрок считается AFK
  timeout: 60
  
  # Сообщение, когда пытаются проверить AFK игрока
  message: "&cИгрок &e{player} &cв данный момент AFK! Дождитесь его возвращения."
  
  # Интервал проверки AFK статуса в секундах (0 - мгновенная проверка)
  check-interval: 0
  
  # Настройки для проверки после выхода из AFK
  post-afk-check:
    # Включить автоматический вызов на проверку после выхода из AFK
    enabled: true
    
    # Задержка вызова на проверку в секундах (0 - мгновенный вызов)
    delay: 0
    
    # Сообщение игроку при выходе из AFK
    message: "&e&lВы вышли из режима AFK и будете вызваны на проверку."
    
    # Сообщение администраторам при автоматическом вызове на проверку
    notification: "&e{player} &aвышел из AFK и был автоматически вызван на проверку."
  
  # Настройки для принудительной проверки (для администраторов)
  force-check:
    # Включить возможность принудительного вызова на проверку
    enabled: true
    
    # Сообщение администратору при принудительном вызове на проверку
    message: "&eИгрок &6{player} &eбыл в AFK, но был принудительно выведен из этого режима."
    
    # Сообщение всем администраторам при принудительном вызове на проверку
    notification: "&c&lВНИМАНИЕ! &e{player} &cбыл принудительно вызван на проверку, несмотря на AFK статус!"

# Настройки сообщений
messages:
  # Префикс для всех сообщений
  prefix: "&8[&c&lCheaterCheck&8] "
  
  # Использовать ActionBar для сообщений
  use-actionbar: true
  
  # Сообщения при проверке
  check:
    # Сообщение при начале проверки
    started: "&aПроверка игрока &e{player} &aначата."
    
    # Сообщение при успешном завершении проверки (игрок чист)
    result-clean: "&aИгрок &e{player} &aбыл проверен и признан чистым."
    
    # Сообщение при бане игрока
    result-banned: "&cИгрок &e{player} &cбыл забанен за использование чита &e{cheat}&c."
    
    # Сообщение о завершении проверки
    completed: "&aПроверка игрока &e{player} &aзавершена."
    
    # Сообщение о перезагрузке
    reload: "&aПлагин был успешно перезагружен!"
  
  # Сообщения при скриншере
  screenshare:
    # Сообщение, отправляемое игроку при запросе скриншера
    request: "&c&lВнимание! &e&lВам необходимо сделать скриншер вашего экрана для проверки.\n&e&lДля этого нажмите клавишу &c&lF2 &e&lи отправьте скриншот администратору."
    
    # Сообщение, отправляемое администратору при запросе скриншера
    request-sent: "&aЗапрос на скриншер отправлен игроку &e{player}&a."
  
  # Сообщения об ошибках
  errors:
    # Сообщение, если у игрока нет права на использование команды
    no-permission: "&cУ вас недостаточно прав для использования этой команды!"
    
    # Сообщение, если игрок не найден
    player-not-found: "&cИгрок не найден!"
    
    # Сообщение, если игрок уже заморожен
    already-frozen: "&cИгрок &e{player} &cуже заморожен!"
    
    # Сообщение, если игрок не заморожен
    not-frozen: "&cИгрок &e{player} &cне заморожен!"
    
    # Сообщение, если игрок в списке байпаса
    bypass-list: "&cИгрок &e{player} &cнаходится в списке игроков, которых нельзя проверить!" 